export const DUMMY = [
  {
    id: 1,
    name: "제주 4·3 평화공원",
    px: 185,
    py: 33,
    fontPx: 180,
    fontPy: 40,
    imageLink: "제주43평화공원",
    status: false,
    address: "",
    scale: 1.2,
  },
  {
    id: 2,
    name: "관덕정",
    px: 173,
    py: 0,
    fontPx: 183,
    fontPy: -10,
    imageLink: "관덕정",
    status: false,
    address: "",
    scale: 1.4,
  },
  {
    id: 3,
    name: "다랑쉬굴",
    px: 232,
    py: 60,
    fontPx: 242,
    fontPy: 50,
    imageLink: "다랑쉬굴",
    status: false,
    address: "",
    scale: 1,
  },
  {
    id: 4,
    name: "곤을동 옛터",
    px: 231,
    py: -3,
    fontPx: 231,
    fontPy: -25,
    imageLink: "곤을동",
    status: false,
    address: "",
    scale: 1,
  },
  {
    id: 5,
    name: "너븐숭이 기념관",
    px: 268,
    py: 3,
    fontPx: 268,
    fontPy: 0,
    imageLink: "너븐숭이",
    status: false,
    address: "",
    scale: 1.2,
  },
  {
    id: 6,
    name: "터진목",
    px: 286,
    py: 43,
    fontPx: 300,
    fontPy: 43,
    imageLink: "터진목",
    status: false,
    address: "",
    scale: 1,
  },
  {
    id: 7,
    name: "한모살",
    px: 257,
    py: 90,
    fontPx: 277,
    fontPy: 100,
    imageLink: "한모살",
    status: false,
    address: "",
    scale: 1,
  },
  {
    id: 8,
    name: "현의합장묘",
    px: 208,
    py: 106,
    fontPx: 210,
    fontPy: 116,
    imageLink: "현의합장묘",
    status: false,
    address: "",
    scale: 1.2,
  },
  {
    id: 9,
    name: "송령이골",
    px: 151,
    py: 82,
    fontPx: 151,
    fontPy: 92,
    imageLink: "송령이골",
    status: false,
    address: "",
    scale: 1,
  },
  {
    id: 10,
    name: "정방폭포",
    px: 105,
    py: 152,
    fontPx: 110,
    fontPy: 147,
    imageLink: "정방폭포",
    status: false,
    address: "",
    scale: 2,
  },
  {
    id: 11,
    name: "백손일손지지",
    px: 7,
    py: 146,
    fontPx: 10,
    fontPy: 148,
    imageLink: "백손일손지지",
    status: false,
    address: "",
    scale: 2,
  },
  {
    id: 12,
    name: "진아영할머니쉼터",
    px: -10,
    py: 95,
    fontPx: 42,
    fontPy: 62,
    imageLink: "진아영할머니쉼터",
    status: false,
    address: "",
    scale: 1.2,
  },
  {
    id: 13,
    name: "빌레못굴",
    px: 39,
    py: 52,
    fontPx: 59,
    fontPy: 42,
    imageLink: "빌레못굴",
    status: false,
    address: "",
    scale: 1.2,
  },
  {
    id: 14,
    name: "영모원",
    px: 90,
    py: 19,
    fontPx: 95,
    fontPy: 26,
    imageLink: "영모원",
    status: false,
    address: "",
    scale: 1,
  },
  {
    id: 15,
    name: "정뜨르 비행장",
    px: 127,
    py: 20,
    fontPx: 127,
    fontPy: 8,
    imageLink: "정뜨르비행장",
    status: false,
    address: "",
    scale: 1.2,
  },
];
